# Generated by Django 5.2.4 on 2025-09-21 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd_models', '0008_alter_ball_options_alter_ballinstance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraftingRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crafted_by', to='bd_models.ball')),
            ],
            options={
                'db_table': 'craftingrecipe',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CraftingIngredientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required_count', models.PositiveIntegerField(default=1)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_groups', to='craftings.craftingrecipe')),
            ],
            options={
                'db_table': 'craftingingredientgroup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CraftingGroupOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='bd_models.ball')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='craftings.craftingingredientgroup')),
            ],
            options={
                'db_table': 'craftinggroupoption',
                'managed': True,
                'unique_together': {('group', 'ball')},
            },
        ),
        migrations.CreateModel(
            name='CraftingIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_models.ball')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='craftings.craftingrecipe')),
            ],
            options={
                'db_table': 'craftingingredient',
                'managed': True,
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
