# Generated by Django 5.1.4 on 2025-05-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
        ('bd_models', '0002_move_upload_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='special_required',
            field=models.ManyToManyField(blank=True, help_text='Any specials', related_name='special_achievement', to='bd_models.special'),
        ),
    ]









