# Generated by Django 5.1.4 on 2025-06-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0002_achievement_special_required'),
        ('bd_models', '0002_move_upload_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='reward',
            field=models.ManyToManyField(
                to='bd_models.ball',
                blank=True,
                help_text='rewards for achievements',
            ),
        ),
    ]
