# Generated by Django 5.1.4 on 2025-06-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0003_achievement_reward'),
        ('bd_models', '0002_move_upload_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='required_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of each required combo (ball + special) needed'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='self_catch',
            field=models.BooleanField(default=False, help_text='weither this achievement need self_catched balls'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='required_balls',
            field=models.ManyToManyField(blank=True, help_text='Which countryballs you need to collect', related_name='achievements', to='bd_models.ball'),
        ),
    ]
